// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pg

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type MaritalStatus string

const (
	MaritalStatusSingle      MaritalStatus = "single"
	MaritalStatusMarried     MaritalStatus = "married"
	MaritalStatusDivorced    MaritalStatus = "divorced"
	MaritalStatusWidowed     MaritalStatus = "widowed"
	MaritalStatusStableUnion MaritalStatus = "stable_union"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus
	Valid         bool // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type Tenant struct {
	ID            uuid.UUID
	Fullname      string
	Rg            string
	Cpf           string
	Occupation    string
	MaritalStatus MaritalStatus
}
