// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: owner.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const deleteOwner = `-- name: DeleteOwner :exec

DELETE FROM
  owner
WHERE id = $1
`

// -------------------------------
func (q *Queries) DeleteOwner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOwner, id)
	return err
}

const getOwner = `-- name: GetOwner :one
SELECT
  id, fullname, rg, cpf, occupation, marital_status
FROM owner
WHERE id = $1
`

func (q *Queries) GetOwner(ctx context.Context, id uuid.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwner, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Rg,
		&i.Cpf,
		&i.Occupation,
		&i.MaritalStatus,
	)
	return i, err
}

const getOwners = `-- name: GetOwners :many

SELECT
  id, fullname, rg, cpf, occupation, marital_status
FROM owner
`

// -------------------------------
func (q *Queries) GetOwners(ctx context.Context) ([]Owner, error) {
	rows, err := q.db.Query(ctx, getOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Owner
	for rows.Next() {
		var i Owner
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Rg,
			&i.Cpf,
			&i.Occupation,
			&i.MaritalStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOwner = `-- name: InsertOwner :one

INSERT INTO owner
  (fullname, rg, cpf, occupation, marital_status) VALUES
  ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertOwnerParams struct {
	Fullname      string        `json:"fullname"`
	Rg            string        `json:"rg"`
	Cpf           string        `json:"cpf"`
	Occupation    string        `json:"occupation"`
	MaritalStatus MaritalStatus `json:"marital_status"`
}

// -------------------------------
func (q *Queries) InsertOwner(ctx context.Context, arg InsertOwnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOwner,
		arg.Fullname,
		arg.Rg,
		arg.Cpf,
		arg.Occupation,
		arg.MaritalStatus,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateOwner = `-- name: UpdateOwner :exec

UPDATE
  owner
SET
  fullname = $1,
  rg = $2,
  cpf = $3,
  occupation = $4,
  marital_status = $5
WHERE id = $6
`

type UpdateOwnerParams struct {
	Fullname      string        `json:"fullname"`
	Rg            string        `json:"rg"`
	Cpf           string        `json:"cpf"`
	Occupation    string        `json:"occupation"`
	MaritalStatus MaritalStatus `json:"marital_status"`
	ID            uuid.UUID     `json:"id"`
}

// -------------------------------
func (q *Queries) UpdateOwner(ctx context.Context, arg UpdateOwnerParams) error {
	_, err := q.db.Exec(ctx, updateOwner,
		arg.Fullname,
		arg.Rg,
		arg.Cpf,
		arg.Occupation,
		arg.MaritalStatus,
		arg.ID,
	)
	return err
}
